server:
  port: 8080
  servlet:
    session:
      cookie:
        name: none
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
  pid:
    file: application.pid
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_laziness: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: techmasterinlab
    password: fjsbeutolwjhpbup
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
logging:
  level:
    org.hibernate.type: TRACE
myapp.max-attempt: 5